# Documentation: http://docs.travis-ci.com/user/languages/c/
image:
  - Visual Studio 2015
  - Visual Studio 2017

cache: c:\tools\vcpkg\installed\

install:
  - set PATH=%PATH%;c:\tools\vcpkg
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - set CC=gcc
  - set BLAS=OPENBLAS
  - cd c:\tools\vcpkg\installed\x64-windows\include
  - ls -all
  - cd c:\tools\vcpkg\installed\x64-windows\include\openblas
  - ls -all
  - cd c:\tools\vcpkg\installed\x64-windows\bin
  - ls -all
  - cd c:\projects\fasttransforms\
  - vcpkg integrate install
  - vcpkg install openblas:x64-windows fftw3:x64-windows

build_script:
  - gcc --version
  #- gcc src/test_win.c -I c:\tools\vcpkg\installed\x64-windows\include -I c:\tools\vcpkg\installed\x64-windows\include\openblas -L c:\tools\vcpkg\installed\x64-windows\bin -lblas -o test_win
  - mingw32-make test_win

test_script:
  - test_win.exe
