# Documentation: http://docs.travis-ci.com/user/languages/c/
image:
  - Visual Studio 2015
  - Visual Studio 2017

cache: c:\tools\vcpkg\installed\

install:
  - set PATH=%PATH%;c:\tools\vcpkg
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - set CC=gcc && set BLAS=OPENBLAS
  - vcpkg integrate install
  - vcpkg install openblas:x64-windows fftw3:x64-windows
  - mklink c:\projects\fasttransforms\src\cblas.h c:\tools\vcpkg\installed\x64-windows\include\openblas\cblas.h
  - mklink c:\projects\fasttransforms\src\openblas_config.h c:\tools\vcpkg\installed\x64-windows\include\openblas\openblas_config.h
  - mklink c:\projects\fasttransforms\blas.dll c:\tools\vcpkg\installed\x64-windows\bin\openblas.dll
  - mklink c:\projects\fasttransforms\src\fftw3.h c:\tools\vcpkg\installed\x64-windows\include\fftw3.h
  - mklink c:\projects\fasttransforms\fftw3.dll c:\tools\vcpkg\installed\x64-windows\bin\fftw3.dll
  - set PATH=c:\tools\vcpkg\installed\x64-windows\bin;%PATH%

build_script:
  - gcc --version
  - mingw32-make lib
  - mingw32-make wintests
  - mingw32-make examples

test_script:
  - test_transforms.exe
  - test_rotations.exe
  - set OMP_NUM_THREADS=4
  - test_drivers.exe 3 3 0
  - additiontheorem.exe
  - holomorphic.exe
