# Documentation: http://docs.travis-ci.com/user/languages/c/
image:
  - Visual Studio 2015
  - Visual Studio 2017

cache: c:\tools\vcpkg\installed\

install:
  - set PATH=%PATH%;c:\tools\vcpkg
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - set CC=gcc
  - set BLAS=OPENBLAS
  - cd c:\tools\vcpkg\installed\x64-windows\include
  - ls -all
  - cd c:\tools\vcpkg\installed\x64-windows\include\openblas
  - ls -all
  - cd c:\tools\vcpkg\installed\x64-windows\bin
  - ls -all
  - cd c:\projects\fasttransforms\
  - vcpkg integrate install
  - vcpkg install openblas:x64-windows fftw3:x64-windows
  - mklink c:\projects\fasttransforms\src\cblas.h c:\tools\vcpkg\installed\x64-windows\include\openblas\cblas.h
  - mklink c:\projects\fasttransforms\blas.dll c:\tools\vcpkg\installed\x64-windows\bin\openblas.dll
  - mklink c:\projects\fasttransforms\src\fftw3.h c:\tools\vcpkg\installed\x64-windows\include\fftw3.h
  - mklink c:\projects\fasttransforms\fftw3.dll c:\tools\vcpkg\installed\x64-windows\bin\fftw3.dll
  #- cd c:\tools\vcpkg\installed\x64-windows\bin
  #- ls -all
  #- cd c:\projects\fasttransforms\
  #- ren c:\tools\vcpkg\installed\x64-windows\include\cblas.h cblas_old.h
  #- mklink c:\tools\vcpkg\installed\x64-windows\include\cblas.h c:\tools\vcpkg\installed\x64-windows\include\openblas\cblas.h
  #- set PATH=c:\tools\vcpkg\installed\x64-windows\bin;%PATH%

build_script:
  - gcc --version
  - mingw32-make test_win

test_script:
  - test_win.exe
