# Documentation: http://www.appveyor.com/docs/appveyor-yml/
image:
  - Visual Studio 2015
  - Visual Studio 2017

cache: c:\tools\vcpkg\installed\

install:
  - set PATH=%PATH%;c:\tools\vcpkg
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - vcpkg install openblas:x64-windows fftw3[core,threads]:x64-windows mpfr:x64-windows mpir:x64-windows --recurse
  - set PATH=c:\tools\vcpkg\installed\x64-windows\bin;%PATH%

build_script:
  - set CC=gcc && set FT_BLAS=openblas && set FT_FFTW_WITH_COMBINED_THREADS=1
  - gcc --version
  - mingw32-make assembly
  - mingw32-make lib
  - mingw32-make tests
  - mingw32-make examples

test_script:
  - set FT_NUM_THREADS=4
  - mingw32-make runtests
  - mingw32-make runexamples
