# Documentation: http://docs.travis-ci.com/user/languages/c/
matrix:
  include:
    # Minimum system requirements
    - os: Visual Studio 2013
      env: MATRIX_EVAL="export CC=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\gcc-7"
    # Recommended system requirements
    - os: Visual Studio 2017
      env: MATRIX_EVAL="export CC=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\gcc-7"

install: eval "${MATRIX_EVAL}"

build_script:
  - gcc --version
  - gcc -v
  - $CC --version
  - $CC -v
  - gcc test_win.c -o test_win

test_script:
  - ./test_win

notifications:
  email: false
