# Documentation: http://docs.travis-ci.com/user/languages/c/
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

install:
  - set PATH=C:\mingw-w64\bin;%PATH%

build_script:
  - g++ --version
  - g++ -v
  - g++ test_win.c -o test_win

test_script:
  - test_win.exe
