# Documentation: http://docs.travis-ci.com/user/languages/c/
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

install:
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - set CC=gcc-7

build_script:
  - "%CC%" --version
  - "%CC%" -v
  - "%CC%" test_win.c -o test_win

test_script:
  - test_win.exe
