# Documentation: http://docs.travis-ci.com/user/languages/c/
image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

install:
  - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1

build_script:
  - gcc --version
  - gcc -v
  - gcc test_win.c -o test_win

test_script:
  - test_win.exe
