# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      compiler: gcc-7
      env:
        - C_COMPILER='gcc-7'
        - MATRIX_EVAL="brew update && brew install gcc@7 openblas fftw"
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libblas-dev
            - libopenblas-base
            - libfftw3-dev
      env:
        - C_COMPILER='gcc-7'
        - MATRIX_EVAL="export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make lib
  - make tests
  - ./test_transforms
  - ./test_rotations
  - OMP_NUM_THREADS=4 ./test_drivers 3 3 0
  - OMP_NUM_THREADS=4 ./test_fftw 3 3 0
  - make examples
  - ./additiontheorem
  - ./holomorphic

notifications:
  email: false
