# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c

jobs:
  include:
    - stage: "Test"
      os: osx
      osx_image: xcode11
      compiler: clang
      addons:
        homebrew:
          packages: ['libomp', 'openblas', 'fftw', 'mpfr']
      env: JOBS_EVAL="export CC=clang"
    - os: osx
      osx_image: xcode11
      compiler: gcc
      addons:
        homebrew:
          packages: ['libomp', 'openblas', 'fftw', 'mpfr']
      env: JOBS_EVAL="export CC=gcc"
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['libomp-dev', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev']
      env: JOBS_EVAL="export CC=clang && export COV=gcov && export FT_COVERAGE=1 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev']
      env: JOBS_EVAL="export CC=gcc && export FT_QUADMATH=1 && export COV=gcov && export FT_COVERAGE=1 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
      after_success:
        - make coverage
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Documentation"
      os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages: doxygen
      script: doxygen Doxyfile
      deploy:
        - provider: pages
          edge: true
          keep_history: false
          local_dir: docs/html
          on:
            branch: master
          token: $FT_DOCS

before_install: eval "${JOBS_EVAL}"

script:
  - make
  - make runtests FT_NUM_THREADS=4
  - make runexamples

notifications:
  email: false
