# Documentation: http://docs.travis-ci.com/user/languages/c/
sudo: true
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew update && brew install gcc openblas fftw && CC=gcc-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libblas-dev
            - libopenblas-base
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."

before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg;
#    fi
  - eval "${MATRIX_EVAL}"

script:
  - make lib
  - make tests
  - ./test_transforms
  - ./test_rotations
  - OMP_NUM_THREADS=4 ./test_drivers 3 3 0
  - OMP_NUM_THREADS=4 ./test_fftw 3 3 0
  - make examples
  - ./additiontheorem
  - ./holomorphic

notifications:
  email: false
