# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c
matrix:
  include:
    - os: osx
      env:
        - MATRIX_EVAL="brew update && brew cask uninstall oclint && brew install gcc openblas fftw && CC=gcc-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libblas-dev
            - libopenblas-base
            - libfftw3-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4";
    fi
  - eval "${MATRIX_EVAL}"

script:
  - make lib
  - make tests
  - ./test_transforms
  - ./test_rotations
  - OMP_NUM_THREADS=4 ./test_drivers 3 3 0
  - OMP_NUM_THREADS=4 ./test_fftw 3 3 0

notifications:
  email: false
