# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c
matrix:
  include:
    # Minimum system requirements
    - os: osx
      osx_image: xcode10
      compiler: gcc-4.9
      env: MATRIX_EVAL="brew update && brew install gcc@4.9 fftw doxygen && export CC=gcc-4.9 && export BLAS=APPLEBLAS"
    # Recommended system requirements
    - os: osx
      osx_image: xcode10
      compiler: gcc-7
      env: MATRIX_EVAL="brew update && brew install gcc@7 fftw doxygen && export CC=gcc-7 && export BLAS=APPLEBLAS"
    # Minimum system requirements
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-4.9', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-4.9 && export BLAS=OPENBLAS && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    # Recommended system requirements
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-7', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-7 && export BLAS=OPENBLAS && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."

before_install: eval "${MATRIX_EVAL}"

script:
  - make lib
  - make tests
  - ./test_transforms
  - ./test_rotations
  - OMP_NUM_THREADS=4 ./test_drivers 3 3 0
  - OMP_NUM_THREADS=4 ./test_fftw 3 3 0
  - make examples
  - ./additiontheorem
  - ./calculus
  - ./holomorphic

after_success:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $FT_DOCS
  on:
    branch: master

notifications:
  email: false
