# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c

jobs:
  include:
    - stage: "Documentation"
      os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages: doxygen
      script: doxygen Doxyfile
      deploy:
        - provider: pages
          cleanup: false
          local_dir: docs/html
          token: $FT_DOCS
          on:
            branch: master

before_install: eval "${JOBS_EVAL}"

script:
  - make
  - ./test_recurrence
  - ./test_transforms
  - ./test_rotations
  - ./test_tridiagonal
  - ./test_hierarchical
  - ./test_banded
  - ./test_dprk
  - ./test_tdc
  - OMP_NUM_THREADS=4 ./test_drivers 1 3 0
  - OMP_NUM_THREADS=4 ./test_fftw 1 3 0
  - ./additiontheorem
  - ./calculus
  - ./holomorphic
  - ./nonlocaldiffusion
  - ./spinweighted

notifications:
  email: false
