# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c

matrix:
  include:
    # Minimum system requirements
    - os: osx
      osx_image: xcode10
      compiler: gcc-4.9
      addons:
        homebrew:
          packages: ['gcc@4.9', 'fftw', 'mpfr', 'doxygen']
          update: true
      env: MATRIX_EVAL="export CC=gcc-4.9 && export FT_USE_APPLEBLAS=1"
    - os: osx
      osx_image: xcode10
      compiler: gcc-5
      addons:
        homebrew:
          packages: ['gcc@5', 'fftw', 'mpfr', 'doxygen']
          update: true
      env: MATRIX_EVAL="export CC=gcc-5 && export FT_USE_APPLEBLAS=1"
    - os: osx
      osx_image: xcode10
      compiler: gcc-6
      addons:
        homebrew:
          packages: ['gcc@6', 'fftw', 'mpfr', 'doxygen']
          update: true
      env: MATRIX_EVAL="export CC=gcc-6 && export FT_USE_APPLEBLAS=1"
    # Recommended system requirements
    - os: osx
      osx_image: xcode10
      compiler: gcc-7
      addons:
        homebrew:
          packages: ['gcc@7', 'fftw', 'mpfr', 'doxygen']
          update: true
      env: MATRIX_EVAL="export CC=gcc-7 && export FT_USE_APPLEBLAS=1"
    - os: osx
      osx_image: xcode10
      compiler: gcc-8
      addons:
        homebrew:
          packages: ['gcc@8', 'fftw', 'mpfr', 'doxygen']
          update: true
      env: MATRIX_EVAL="export CC=gcc-8 && export FT_USE_APPLEBLAS=1"
    - os: osx
      osx_image: xcode10
      compiler: gcc-9
      addons:
        homebrew:
          packages: ['gcc@9', 'fftw', 'mpfr', 'doxygen']
          update: true
      env: MATRIX_EVAL="export CC=gcc-9 && export FT_USE_APPLEBLAS=1"
    # Minimum system requirements
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-4.9', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-4.9 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-5', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-5 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-6', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-6 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    # Recommended system requirements
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-7', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-7 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    - os: linux
      compiler: gcc-8
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-8', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-8 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."
    - os: linux
      compiler: gcc-9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ['gcc-9', 'libblas-dev', 'libopenblas-base', 'libfftw3-dev', 'libmpfr-dev', 'doxygen']
      env: MATRIX_EVAL="export CC=gcc-9 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:."

before_install: eval "${MATRIX_EVAL}"

script:
  - make
  #- ./test_recurrence
  - ./test_transforms
  - ./test_rotations
  - ./test_tridiagonal
  - ./test_hierarchical
  - ./test_banded
  - ./test_dprk
  - ./test_tdc
  - OMP_NUM_THREADS=4 ./test_drivers 3 3 0
  - OMP_NUM_THREADS=4 ./test_fftw 3 3 0
  - ./additiontheorem
  - ./calculus
  - ./holomorphic
  - ./nonlocaldiffusion

after_success:
  - doxygen Doxyfile

before_deploy:
  - ./travis_deploy.sh

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $FT_DOCS
    on:
      branch: master
  - provider: releases
    api_key: $FT_BINARIES
    file_glob: true
    file: libfasttransforms.*
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
