var searchData=
[
  ['ft_5fannulus_5ffftw_5fplan_0',['ft_annulus_fftw_plan',['../structft__annulus__fftw__plan.html',1,'']]],
  ['ft_5fdisk_5ffftw_5fplan_1',['ft_disk_fftw_plan',['../structft__disk__fftw__plan.html',1,'']]],
  ['ft_5fgradient_5fplan_2',['ft_gradient_plan',['../structft__gradient__plan.html',1,'']]],
  ['ft_5fharmonic_5fplan_3',['ft_harmonic_plan',['../structft__harmonic__plan.html',1,'']]],
  ['ft_5fhelmholtzhodge_5fplan_4',['ft_helmholtzhodge_plan',['../structft__helmholtzhodge__plan.html',1,'']]],
  ['ft_5fmpfr_5ftriangular_5fbanded_5',['ft_mpfr_triangular_banded',['../structft__mpfr__triangular__banded.html',1,'']]],
  ['ft_5forthogonal_5ftransformation_6',['ft_orthogonal_transformation',['../structft__orthogonal__transformation.html',1,'']]],
  ['ft_5fpartial_5fsph_5fisometry_5fplan_7',['ft_partial_sph_isometry_plan',['../structft__partial__sph__isometry__plan.html',1,'']]],
  ['ft_5frectdisk_5ffftw_5fplan_8',['ft_rectdisk_fftw_plan',['../structft__rectdisk__fftw__plan.html',1,'']]],
  ['ft_5freflection_9',['ft_reflection',['../structft__reflection.html',1,'']]],
  ['ft_5fsph_5fisometry_5fplan_10',['ft_sph_isometry_plan',['../structft__sph__isometry__plan.html',1,'']]],
  ['ft_5fsphere_5ffftw_5fplan_11',['ft_sphere_fftw_plan',['../structft__sphere__fftw__plan.html',1,'']]],
  ['ft_5fspin_5fharmonic_5fplan_12',['ft_spin_harmonic_plan',['../structft__spin__harmonic__plan.html',1,'']]],
  ['ft_5fspinsphere_5ffftw_5fplan_13',['ft_spinsphere_fftw_plan',['../structft__spinsphere__fftw__plan.html',1,'']]],
  ['ft_5ftetrahedron_5ffftw_5fplan_14',['ft_tetrahedron_fftw_plan',['../structft__tetrahedron__fftw__plan.html',1,'']]],
  ['ft_5ftriangle_5ffftw_5fplan_15',['ft_triangle_fftw_plan',['../structft__triangle__fftw__plan.html',1,'']]],
  ['ft_5fzyzr_16',['ft_ZYZR',['../structft___z_y_z_r.html',1,'']]]
];
