void X(checktest)(FLT err, FLT cst, int * checksum);
FLT X(norm_1arg)(FLT * A, int n);
FLT X(norm_2arg)(FLT * A, FLT * B, int n);
FLT X(normInf_1arg)(FLT * A, int n);
FLT X(normInf_2arg)(FLT * A, FLT * B, int n);
FLT X(rec_A_jacobi)(const int norm, const int n, const FLT alpha, const FLT beta);
FLT X(rec_B_jacobi)(const int norm, const int n, const FLT alpha, const FLT beta);
FLT X(rec_C_jacobi)(const int norm, const int n, const FLT alpha, const FLT beta);
FLT X(rec_A_laguerre)(const int norm, const int n, const FLT alpha);
FLT X(rec_B_laguerre)(const int norm, const int n, const FLT alpha);
FLT X(rec_C_laguerre)(const int norm, const int n, const FLT alpha);
FLT X(rec_A_hermite)(const int norm, const int n);
FLT X(rec_B_hermite)(const int norm, const int n);
FLT X(rec_C_hermite)(const int norm, const int n);
