name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: C - ${{ matrix.os }} - ${{ matrix.compiler }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x86
          - x64
        exclude:
          - os: macOS-latest
            arch: x86
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libomp-dev libblas-dev libopenblas-base libfftw3-dev libmpfr-dev
          export CC=${{ matrix.compiler }}
        env:
          LD_LIBRARY_PATH: .
      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew update
          brew install libomp openblas fftw mpfr
          export CC=${{ matrix.compiler }}
      - name: Compiler version
        run: cc --version
      - name: Build library
        run: make
      - name: Run tests
        run: make runtests FT_NUM_THREADS=2
      - name: Run examples
        run: make runexamples
