name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: C ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x86
          - x64
        exclude:
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew update
          brew install libomp openblas fftw mpfr
          export CC=${{ matrix.compiler }}
      - name: Build library
        run: make
      - name: Run tests
        run: make runtests FT_NUM_THREADS=2
      - name: Run examples
        run: make runexamples
