name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: C - ${{ matrix.os }} - ${{ matrix.compiler }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          #- windows-latest
        compiler:
          - gcc
          - clang
        arch:
          - x86
          - x64
          - aarch64
        exclude:
          - os: macOS-latest
            arch: x86
          - os: macOS-latest
            arch: aarch64
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libomp-dev libblas-dev libopenblas-base libfftw3-dev libmpfr-dev
      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew update
          brew install libomp openblas fftw mpfr
      - name: Compiler version
        run: cc --version
      - name: Build assembly
        run: make assembly CC=${{ matrix.compiler }}
      - name: Build library
        run: make lib CC=${{ matrix.compiler }}
      - name: Build tests
        run: make tests CC=${{ matrix.compiler }}
      - name: Build examples
        run: make examples CC=${{ matrix.compiler }}
      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:.
          make runtests CC=${{ matrix.compiler }} FT_NUM_THREADS=2
      - name: Run examples
        run: |
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:.
          make runexamples CC=${{ matrix.compiler }}
